DELETE_STATUS = 0
DELETED = 1
LIST_RECORD_STATUS = 50
NO_SERVICE_POOLS_TO_DELETE = "No service pools to delete"
SERVICE_POOL_NOT_FOUND = "Service pool not found"
UNABLE_TO_DELETE_POOL = "The <pool-name> pool is used for <services-list>. You must remove it from <the> service before deleting this pool."
DELETE = "DELETE"
RECORD_STATUS = 1
DATA_INSERT_SUCCESSFUL = "Data inserted succesfully."
UNIQUE_POOL_NAME = "Pool name must be unique."
DATA_UPDATE_SUCCESSFUL = "Data updated succesfully."
POOL_NOT_FOUND = "Pool not found."
THAT = "that"
EACH = "each"
ERROR_ON_HISTORY_TABLE_INSERT = "Error on history table insert"
REDUCE_DATE_MESSAGE = "There are bookings made during the period you have excluded from this date range using this service pool. Do you want to continue?"
REDUCE_CAPACITY_MESSSAGE = "Bookings already exceed the new capacity limit. Proceed with reducing capacity?"
REDUCED_DATE_CAPACITY_MESSAGE = "Bookings exceed the new capacity for the excluded dates. Shall we proceed with reducing the date range and capacity?"
PAST_DATE_ERROR ="Dates in the past are not allowed"
DATE_VALIDATION = "Start date cannot be after end date"
CHECK_CAPACITY_TYPE_ID = 2